package Exceptions.exception_intro.exampletesttt;

public class demo1 {


    public static void main(String[] args) {
        try{
            System.out.println("this is insdie try block");
        }
        catch (Exception e){

        }
        System.out.println("this is outside try-catch block");
    }
}
